.TH XMPSOLVE "1" "March 2013" "xmpsolve 3.1.2" "User Commands"
.SH NAME
xmpsolve \- Graphical interface to MPSolve, a multiprecision polynomial rootfinder 
.SH DESCRIPTION
xmpsolve
.SH OPTIONS
This program has no command line options. 
.SH "SEE ALSO"
The full documentation for
.B xmpsolve
is maintained as a Texinfo manual.  If the
.B info
and
.B xmpsolve
programs are properly installed at your site, the command
.IP
.B info xmpsolve
.PP
should give you access to the complete manual.
